mod fcitx_enum {
    
    #[repr(u32)]
    enum FcitxKeySym {
        FcitxKey_None = 0x0,
        FcitxKey_VoidSymbol = 0xffffff, /* Void symbol */
        FcitxKey_BackSpace = 0xff08,    /* Back space, back char */
        FcitxKey_Tab = 0xff09,
        FcitxKey_Linefeed = 0xff0a, /* Linefeed, LF */
        FcitxKey_Clear = 0xff0b,
        FcitxKey_Return = 0xff0d, /* Return, enter */
        FcitxKey_Pause = 0xff13,  /* Pause, hold */
        FcitxKey_Scroll_Lock = 0xff14,
        FcitxKey_Sys_Req = 0xff15,
        FcitxKey_Escape = 0xff1b,
        FcitxKey_Delete = 0xffff,    /* Delete, rubout */
        FcitxKey_Multi_key = 0xff20, /* Multi-key character compose */
        FcitxKey_Codeinput = 0xff37,
        FcitxKey_SingleCandidate = 0xff3c,
        FcitxKey_MultipleCandidate = 0xff3d,
        FcitxKey_PreviousCandidate = 0xff3e,
        FcitxKey_Home = 0xff50,
        FcitxKey_Left = 0xff51,  /* Move left, left arrow */
        FcitxKey_Up = 0xff52,    /* Move up, up arrow */
        FcitxKey_Right = 0xff53, /* Move right, right arrow */
        FcitxKey_Down = 0xff54,  /* Move down, down arrow */
        FcitxKey_Page_Up = 0xff55,
        FcitxKey_Page_Down = 0xff56,
        FcitxKey_End = 0xff57,    /* EOL */
        FcitxKey_Begin = 0xff58,  /* BOL */
        FcitxKey_Select = 0xff60, /* Select, mark */
        FcitxKey_Print = 0xff61,
        FcitxKey_Execute = 0xff62, /* Execute, run, do */
        FcitxKey_Insert = 0xff63,  /* Insert, insert here */
        FcitxKey_Undo = 0xff65,
        FcitxKey_Redo = 0xff66, /* Redo, again */
        FcitxKey_Menu = 0xff67,
        FcitxKey_Find = 0xff68,   /* Find, search */
        FcitxKey_Cancel = 0xff69, /* Cancel, stop, abort, exit */
        FcitxKey_Help = 0xff6a,   /* Help */
        FcitxKey_Break = 0xff6b,
        FcitxKey_Num_Lock = 0xff7f,
        FcitxKey_F1 = 0xffbe,
        FcitxKey_F2 = 0xffbf,
        FcitxKey_F3 = 0xffc0,
        FcitxKey_F4 = 0xffc1,
        FcitxKey_F5 = 0xffc2,
        FcitxKey_F6 = 0xffc3,
        FcitxKey_F7 = 0xffc4,
        FcitxKey_F8 = 0xffc5,
        FcitxKey_F9 = 0xffc6,
        FcitxKey_F10 = 0xffc7,
        FcitxKey_F11 = 0xffc8,
        FcitxKey_F12 = 0xffc9,
        FcitxKey_Shift_L = 0xffe1,    /* Left shift */
        FcitxKey_Shift_R = 0xffe2,    /* Right shift */
        FcitxKey_Control_L = 0xffe3,  /* Left control */
        FcitxKey_Control_R = 0xffe4,  /* Right control */
        FcitxKey_Caps_Lock = 0xffe5,  /* Caps lock */
        FcitxKey_Shift_Lock = 0xffe6, /* Shift lock */
        FcitxKey_Meta_L = 0xffe7,     /* Left meta */
        FcitxKey_Meta_R = 0xffe8,     /* Right meta */
        FcitxKey_Alt_L = 0xffe9,      /* Left alt */
        FcitxKey_Alt_R = 0xffea,      /* Right alt */
        FcitxKey_Super_L = 0xffeb,    /* Left super */
        FcitxKey_Super_R = 0xffec,    /* Right super */
        FcitxKey_Hyper_L = 0xffed,    /* Left hyper */
        FcitxKey_Hyper_R = 0xffee,    /* Right hyper */
        FcitxKey_First_Virtual_Screen = 0xfed0,
        FcitxKey_Prev_Virtual_Screen = 0xfed1,
        FcitxKey_Next_Virtual_Screen = 0xfed2,
        FcitxKey_Last_Virtual_Screen = 0xfed4,
        FcitxKey_Terminate_Server = 0xfed5,
        FcitxKey_AccessX_Enable = 0xfe70,
        FcitxKey_AccessX_Feedback_Enable = 0xfe71,
        FcitxKey_RepeatKeys_Enable = 0xfe72,
        FcitxKey_SlowKeys_Enable = 0xfe73,
        FcitxKey_BounceKeys_Enable = 0xfe74,
        FcitxKey_StickyKeys_Enable = 0xfe75,
        FcitxKey_MouseKeys_Enable = 0xfe76,
        FcitxKey_MouseKeys_Accel_Enable = 0xfe77,
        FcitxKey_Overlay1_Enable = 0xfe78,
        FcitxKey_Overlay2_Enable = 0xfe79,
        FcitxKey_AudibleBell_Enable = 0xfe7a,
        FcitxKey_Pointer_Left = 0xfee0,
        FcitxKey_Pointer_Right = 0xfee1,
        FcitxKey_Pointer_Up = 0xfee2,
        FcitxKey_Pointer_Down = 0xfee3,
        FcitxKey_Pointer_UpLeft = 0xfee4,
        FcitxKey_Pointer_UpRight = 0xfee5,
        FcitxKey_Pointer_DownLeft = 0xfee6,
        FcitxKey_Pointer_DownRight = 0xfee7,
        FcitxKey_Pointer_Button_Dflt = 0xfee8,
        FcitxKey_Pointer_Button1 = 0xfee9,
        FcitxKey_Pointer_Button2 = 0xfeea,
        FcitxKey_Pointer_Button3 = 0xfeeb,
        FcitxKey_Pointer_Button4 = 0xfeec,
        FcitxKey_Pointer_Button5 = 0xfeed,
        FcitxKey_Pointer_DblClick_Dflt = 0xfeee,
        FcitxKey_Pointer_DblClick1 = 0xfeef,
        FcitxKey_Pointer_DblClick2 = 0xfef0,
        FcitxKey_Pointer_DblClick3 = 0xfef1,
        FcitxKey_Pointer_DblClick4 = 0xfef2,
        FcitxKey_Pointer_DblClick5 = 0xfef3,
        FcitxKey_Pointer_Drag_Dflt = 0xfef4,
        FcitxKey_Pointer_Drag1 = 0xfef5,
        FcitxKey_Pointer_Drag2 = 0xfef6,
        FcitxKey_Pointer_Drag3 = 0xfef7,
        FcitxKey_Pointer_Drag4 = 0xfef8,
        FcitxKey_Pointer_Drag5 = 0xfefd,
        FcitxKey_Pointer_EnableKeys = 0xfef9,
        FcitxKey_Pointer_Accelerate = 0xfefa,
        FcitxKey_Pointer_DfltBtnNext = 0xfefb,
        FcitxKey_Pointer_DfltBtnPrev = 0xfefc,
        FcitxKey_space = 0x0020,                       /* U+0020 SPACE */
        FcitxKey_exclam = 0x0021,                      /* U+0021 EXCLAMATION MARK */
        FcitxKey_quotedbl = 0x0022,                    /* U+0022 QUOTATION MARK */
        FcitxKey_numbersign = 0x0023,                  /* U+0023 NUMBER SIGN */
        FcitxKey_dollar = 0x0024,                      /* U+0024 DOLLAR SIGN */
        FcitxKey_percent = 0x0025,                     /* U+0025 PERCENT SIGN */
        FcitxKey_ampersand = 0x0026,                   /* U+0026 AMPERSAND */
        FcitxKey_apostrophe = 0x0027,                  /* U+0027 APOSTROPHE */
        FcitxKey_parenleft = 0x0028,                   /* U+0028 LEFT PARENTHESIS */
        FcitxKey_parenright = 0x0029,                  /* U+0029 RIGHT PARENTHESIS */
        FcitxKey_asterisk = 0x002a,                    /* U+002A ASTERISK */
        FcitxKey_plus = 0x002b,                        /* U+002B PLUS SIGN */
        FcitxKey_comma = 0x002c,                       /* U+002C COMMA */
        FcitxKey_minus = 0x002d,                       /* U+002D HYPHEN-MINUS */
        FcitxKey_period = 0x002e,                      /* U+002E FULL STOP */
        FcitxKey_slash = 0x002f,                       /* U+002F SOLIDUS */
        FcitxKey_0 = 0x0030,                           /* U+0030 DIGIT ZERO */
        FcitxKey_1 = 0x0031,                           /* U+0031 DIGIT ONE */
        FcitxKey_2 = 0x0032,                           /* U+0032 DIGIT TWO */
        FcitxKey_3 = 0x0033,                           /* U+0033 DIGIT THREE */
        FcitxKey_4 = 0x0034,                           /* U+0034 DIGIT FOUR */
        FcitxKey_5 = 0x0035,                           /* U+0035 DIGIT FIVE */
        FcitxKey_6 = 0x0036,                           /* U+0036 DIGIT SIX */
        FcitxKey_7 = 0x0037,                           /* U+0037 DIGIT SEVEN */
        FcitxKey_8 = 0x0038,                           /* U+0038 DIGIT EIGHT */
        FcitxKey_9 = 0x0039,                           /* U+0039 DIGIT NINE */
        FcitxKey_colon = 0x003a,                       /* U+003A COLON */
        FcitxKey_semicolon = 0x003b,                   /* U+003B SEMICOLON */
        FcitxKey_less = 0x003c,                        /* U+003C LESS-THAN SIGN */
        FcitxKey_equal = 0x003d,                       /* U+003D EQUALS SIGN */
        FcitxKey_greater = 0x003e,                     /* U+003E GREATER-THAN SIGN */
        FcitxKey_question = 0x003f,                    /* U+003F QUESTION MARK */
        FcitxKey_at = 0x0040,                          /* U+0040 COMMERCIAL AT */
        FcitxKey_A = 0x0041,                           /* U+0041 LATIN CAPITAL LETTER A */
        FcitxKey_B = 0x0042,                           /* U+0042 LATIN CAPITAL LETTER B */
        FcitxKey_C = 0x0043,                           /* U+0043 LATIN CAPITAL LETTER C */
        FcitxKey_D = 0x0044,                           /* U+0044 LATIN CAPITAL LETTER D */
        FcitxKey_E = 0x0045,                           /* U+0045 LATIN CAPITAL LETTER E */
        FcitxKey_F = 0x0046,                           /* U+0046 LATIN CAPITAL LETTER F */
        FcitxKey_G = 0x0047,                           /* U+0047 LATIN CAPITAL LETTER G */
        FcitxKey_H = 0x0048,                           /* U+0048 LATIN CAPITAL LETTER H */
        FcitxKey_I = 0x0049,                           /* U+0049 LATIN CAPITAL LETTER I */
        FcitxKey_J = 0x004a,                           /* U+004A LATIN CAPITAL LETTER J */
        FcitxKey_K = 0x004b,                           /* U+004B LATIN CAPITAL LETTER K */
        FcitxKey_L = 0x004c,                           /* U+004C LATIN CAPITAL LETTER L */
        FcitxKey_M = 0x004d,                           /* U+004D LATIN CAPITAL LETTER M */
        FcitxKey_N = 0x004e,                           /* U+004E LATIN CAPITAL LETTER N */
        FcitxKey_O = 0x004f,                           /* U+004F LATIN CAPITAL LETTER O */
        FcitxKey_P = 0x0050,                           /* U+0050 LATIN CAPITAL LETTER P */
        FcitxKey_Q = 0x0051,                           /* U+0051 LATIN CAPITAL LETTER Q */
        FcitxKey_R = 0x0052,                           /* U+0052 LATIN CAPITAL LETTER R */
        FcitxKey_S = 0x0053,                           /* U+0053 LATIN CAPITAL LETTER S */
        FcitxKey_T = 0x0054,                           /* U+0054 LATIN CAPITAL LETTER T */
        FcitxKey_U = 0x0055,                           /* U+0055 LATIN CAPITAL LETTER U */
        FcitxKey_V = 0x0056,                           /* U+0056 LATIN CAPITAL LETTER V */
        FcitxKey_W = 0x0057,                           /* U+0057 LATIN CAPITAL LETTER W */
        FcitxKey_X = 0x0058,                           /* U+0058 LATIN CAPITAL LETTER X */
        FcitxKey_Y = 0x0059,                           /* U+0059 LATIN CAPITAL LETTER Y */
        FcitxKey_Z = 0x005a,                           /* U+005A LATIN CAPITAL LETTER Z */
        FcitxKey_bracketleft = 0x005b,                 /* U+005B LEFT SQUARE BRACKET */
        FcitxKey_backslash = 0x005c,                   /* U+005C REVERSE SOLIDUS */
        FcitxKey_bracketright = 0x005d,                /* U+005D RIGHT SQUARE BRACKET */
        FcitxKey_asciicircum = 0x005e,                 /* U+005E CIRCUMFLEX ACCENT */
        FcitxKey_underscore = 0x005f,                  /* U+005F LOW LINE */
        FcitxKey_grave = 0x0060,                       /* U+0060 GRAVE ACCENT */
        FcitxKey_a = 0x0061,                           /* U+0061 LATIN SMALL LETTER A */
        FcitxKey_b = 0x0062,                           /* U+0062 LATIN SMALL LETTER B */
        FcitxKey_c = 0x0063,                           /* U+0063 LATIN SMALL LETTER C */
        FcitxKey_d = 0x0064,                           /* U+0064 LATIN SMALL LETTER D */
        FcitxKey_e = 0x0065,                           /* U+0065 LATIN SMALL LETTER E */
        FcitxKey_f = 0x0066,                           /* U+0066 LATIN SMALL LETTER F */
        FcitxKey_g = 0x0067,                           /* U+0067 LATIN SMALL LETTER G */
        FcitxKey_h = 0x0068,                           /* U+0068 LATIN SMALL LETTER H */
        FcitxKey_i = 0x0069,                           /* U+0069 LATIN SMALL LETTER I */
        FcitxKey_j = 0x006a,                           /* U+006A LATIN SMALL LETTER J */
        FcitxKey_k = 0x006b,                           /* U+006B LATIN SMALL LETTER K */
        FcitxKey_l = 0x006c,                           /* U+006C LATIN SMALL LETTER L */
        FcitxKey_m = 0x006d,                           /* U+006D LATIN SMALL LETTER M */
        FcitxKey_n = 0x006e,                           /* U+006E LATIN SMALL LETTER N */
        FcitxKey_o = 0x006f,                           /* U+006F LATIN SMALL LETTER O */
        FcitxKey_p = 0x0070,                           /* U+0070 LATIN SMALL LETTER P */
        FcitxKey_q = 0x0071,                           /* U+0071 LATIN SMALL LETTER Q */
        FcitxKey_r = 0x0072,                           /* U+0072 LATIN SMALL LETTER R */
        FcitxKey_s = 0x0073,                           /* U+0073 LATIN SMALL LETTER S */
        FcitxKey_t = 0x0074,                           /* U+0074 LATIN SMALL LETTER T */
        FcitxKey_u = 0x0075,                           /* U+0075 LATIN SMALL LETTER U */
        FcitxKey_v = 0x0076,                           /* U+0076 LATIN SMALL LETTER V */
        FcitxKey_w = 0x0077,                           /* U+0077 LATIN SMALL LETTER W */
        FcitxKey_x = 0x0078,                           /* U+0078 LATIN SMALL LETTER X */
        FcitxKey_y = 0x0079,                           /* U+0079 LATIN SMALL LETTER Y */
        FcitxKey_z = 0x007a,                           /* U+007A LATIN SMALL LETTER Z */
        FcitxKey_braceleft = 0x007b,                   /* U+007B LEFT CURLY BRACKET */
        FcitxKey_bar = 0x007c,                         /* U+007C VERTICAL LINE */
        FcitxKey_braceright = 0x007d,                  /* U+007D RIGHT CURLY BRACKET */
        FcitxKey_asciitilde = 0x007e,                  /* U+007E TILDE */
        FcitxKey_nobreakspace = 0x00a0,                /* U+00A0 NO-BREAK SPACE */
        FcitxKey_exclamdown = 0x00a1,                  /* U+00A1 INVERTED EXCLAMATION MARK */
        FcitxKey_cent = 0x00a2,                        /* U+00A2 CENT SIGN */
        FcitxKey_sterling = 0x00a3,                    /* U+00A3 POUND SIGN */
        FcitxKey_currency = 0x00a4,                    /* U+00A4 CURRENCY SIGN */
        FcitxKey_yen = 0x00a5,                         /* U+00A5 YEN SIGN */
    }
}
