[package]
name = "rust-part"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"
name = "mylib"

[[bin]]
name = "myapp"
path = "src/main.rs"

[dependencies]