//! # DBus interface proxies for: `org.freedesktop.IBus.Service`, `org.freedesktop.IBus.Factory`, `org.freedesktop.IBus.Service`, `org.freedesktop.IBus.Engine`, `org.freedesktop.IBus.Panel`
//!
//! This code was generated by `zbus-xmlgen` `3.1.0` from DBus introspection data.
//! Source: `interfaces.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(interface = "org.freedesktop.IBus.Engine", assume_defaults = true)]
trait Engine {
    /// CancelHandWriting method
    fn cancel_hand_writing(&self, n_strokes: u32) -> zbus::Result<()>;

    /// CandidateClicked method
    fn candidate_clicked(&self, index: u32, button: u32, state: u32) -> zbus::Result<()>;

    /// CursorDown method
    fn cursor_down(&self) -> zbus::Result<()>;

    /// CursorUp method
    fn cursor_up(&self) -> zbus::Result<()>;

    /// Disable method
    fn disable(&self) -> zbus::Result<()>;

    /// Enable method
    fn enable(&self) -> zbus::Result<()>;

    /// FocusIn method
    fn focus_in(&self) -> zbus::Result<()>;

    /// FocusInId method
    fn focus_in_id(&self, object_path: &str, client: &str) -> zbus::Result<()>;

    /// FocusOut method
    fn focus_out(&self) -> zbus::Result<()>;

    /// FocusOutId method
    fn focus_out_id(&self, object_path: &str) -> zbus::Result<()>;

    /// PageDown method
    fn page_down(&self) -> zbus::Result<()>;

    /// PageUp method
    fn page_up(&self) -> zbus::Result<()>;

    /// PanelExtensionReceived method
    fn panel_extension_received(&self, event: &zbus::zvariant::Value<'_>) -> zbus::Result<()>;

    /// PanelExtensionRegisterKeys method
    fn panel_extension_register_keys(&self, data: &zbus::zvariant::Value<'_>) -> zbus::Result<()>;

    /// ProcessHandWritingEvent method
    fn process_hand_writing_event(&self, coordinates: &[f64]) -> zbus::Result<()>;

    /// ProcessKeyEvent method
    fn process_key_event(&self, keyval: u32, keycode: u32, state: u32) -> zbus::Result<bool>;

    /// PropertyActivate method
    fn property_activate(&self, name: &str, state: u32) -> zbus::Result<()>;

    /// PropertyHide method
    fn property_hide(&self, name: &str) -> zbus::Result<()>;

    /// PropertyShow method
    fn property_show(&self, name: &str) -> zbus::Result<()>;

    /// Reset method
    fn reset(&self) -> zbus::Result<()>;

    /// SetCapabilities method
    fn set_capabilities(&self, caps: u32) -> zbus::Result<()>;

    /// SetCursorLocation method
    fn set_cursor_location(&self, x: i32, y: i32, w: i32, h: i32) -> zbus::Result<()>;

    /// SetSurroundingText method
    fn set_surrounding_text(
        &self,
        text: &zbus::zvariant::Value<'_>,
        cursor_pos: u32,
        anchor_pos: u32,
    ) -> zbus::Result<()>;

    /// CommitText signal
    #[dbus_proxy(signal)]
    fn commit_text(&self, text: zbus::zvariant::Value<'_>) -> zbus::Result<()>;

    /// ForwardKeyEvent signal
    #[dbus_proxy(signal)]
    fn forward_key_event(&self, keyval: u32, keycode: u32, state: u32) -> zbus::Result<()>;

    /// PanelExtension signal
    #[dbus_proxy(signal)]
    fn panel_extension(&self, data: zbus::zvariant::Value<'_>) -> zbus::Result<()>;

    /// RegisterProperties signal
    #[dbus_proxy(signal)]
    fn register_properties(&self, props: zbus::zvariant::Value<'_>) -> zbus::Result<()>;

    /// UpdateAuxiliaryText signal
    #[dbus_proxy(signal)]
    fn update_auxiliary_text(
        &self,
        text: zbus::zvariant::Value<'_>,
        visible: bool,
    ) -> zbus::Result<()>;

    /// UpdateLookupTable signal
    #[dbus_proxy(signal)]
    fn update_lookup_table(
        &self,
        table: zbus::zvariant::Value<'_>,
        visible: bool,
    ) -> zbus::Result<()>;

    /// UpdatePreeditText signal
    #[dbus_proxy(signal)]
    fn update_preedit_text(
        &self,
        text: zbus::zvariant::Value<'_>,
        cursor_pos: u32,
        visible: bool,
        mode: u32,
    ) -> zbus::Result<()>;

    /// UpdateProperty signal
    #[dbus_proxy(signal)]
    fn update_property(&self, prop: zbus::zvariant::Value<'_>) -> zbus::Result<()>;

    /// ActiveSurroundingText property
    #[dbus_proxy(property)]
    fn active_surrounding_text(&self) -> zbus::Result<bool>;

    /// FocusId property
    #[dbus_proxy(property)]
    fn focus_id(&self) -> zbus::Result<bool>;
}