// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fcitx_to_fcp.proto

#include "fcitx_to_fcp.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_fcitx_5fto_5ffcp_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_fcitx_5fto_5ffcp_2eproto = nullptr;
const ::uint32_t TableStruct_fcitx_5fto_5ffcp_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_fcitx_5fto_5ffcp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\022fcitx_to_fcp.proto*\351\007\n\010KeyEvent\022\t\n\005NUM"
    "_0\020\000\022\t\n\005NUM_1\020\001\022\t\n\005NUM_2\020\002\022\t\n\005NUM_3\020\003\022\t\n"
    "\005NUM_4\020\004\022\t\n\005NUM_5\020\005\022\t\n\005NUM_6\020\006\022\t\n\005NUM_7\020"
    "\007\022\t\n\005NUM_8\020\010\022\t\n\005NUM_9\020\t\022\t\n\005A_LWR\020d\022\t\n\005B_"
    "LWR\020e\022\t\n\005C_LWR\020f\022\t\n\005D_LWR\020g\022\t\n\005E_LWR\020h\022\t"
    "\n\005F_LWR\020i\022\t\n\005G_LWR\020j\022\t\n\005H_LWR\020k\022\t\n\005I_LWR"
    "\020l\022\t\n\005J_LWR\020m\022\t\n\005K_LWR\020n\022\t\n\005L_LWR\020o\022\t\n\005M"
    "_LWR\020p\022\t\n\005N_LWR\020q\022\t\n\005O_LWR\020r\022\t\n\005P_LWR\020s\022"
    "\t\n\005Q_LWR\020t\022\t\n\005R_LWR\020u\022\t\n\005S_LWR\020v\022\t\n\005T_LW"
    "R\020w\022\t\n\005U_LWR\020x\022\t\n\005V_LWR\020y\022\t\n\005W_LWR\020z\022\t\n\005"
    "X_LWR\020{\022\t\n\005Y_LWR\020|\022\t\n\005Z_LWR\020}\022\n\n\005A_UPR\020\310"
    "\001\022\n\n\005B_UPR\020\311\001\022\n\n\005C_UPR\020\312\001\022\n\n\005D_UPR\020\313\001\022\n\n"
    "\005E_UPR\020\314\001\022\n\n\005F_UPR\020\315\001\022\n\n\005G_UPR\020\316\001\022\n\n\005H_U"
    "PR\020\317\001\022\n\n\005I_UPR\020\320\001\022\n\n\005J_UPR\020\321\001\022\n\n\005K_UPR\020\322"
    "\001\022\n\n\005L_UPR\020\323\001\022\n\n\005M_UPR\020\324\001\022\n\n\005N_UPR\020\325\001\022\n\n"
    "\005O_UPR\020\326\001\022\n\n\005P_UPR\020\327\001\022\n\n\005Q_UPR\020\330\001\022\n\n\005R_U"
    "PR\020\331\001\022\n\n\005S_UPR\020\332\001\022\n\n\005T_UPR\020\333\001\022\n\n\005U_UPR\020\334"
    "\001\022\n\n\005V_UPR\020\335\001\022\n\n\005W_UPR\020\336\001\022\n\n\005X_UPR\020\337\001\022\n\n"
    "\005Y_UPR\020\340\001\022\n\n\005Z_UPR\020\341\001\022\t\n\005COMMA\020\n\022\n\n\006PERI"
    "OD\020\013\022\r\n\tQEST_MARK\020\014\022\r\n\tEXCL_MARK\020\r\022\016\n\nSE"
    "MI_COLON\020\016\022\r\n\tDBL_QUOTE\020\017\022\r\n\tSGL_QUOTE\020\020"
    "\022\r\n\tBRKT_OPEN\020\021\022\016\n\nBRKT_CLOSE\020\022\022\t\n\005SLASH"
    "\020\023\022\r\n\tBACKSLASH\020\024\022\014\n\010ELLIPSIS\020\025\022\t\n\005ENTER"
    "\020\036\022\t\n\005SPACE\020\037\022\t\n\005MINUS\020 \022\t\n\005EQUAL\020!\022\006\n\002U"
    "P\020(\022\010\n\004DOWN\020)\022\010\n\004LEFT\020*\022\t\n\005RIGHT\020+\022\t\n\005SH"
    "IFT\0202\022\010\n\004CTRL\0203\022\007\n\003ALT\0204b\006proto3"
};
static ::absl::once_flag descriptor_table_fcitx_5fto_5ffcp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fcitx_5fto_5ffcp_2eproto = {
    false,
    false,
    1032,
    descriptor_table_protodef_fcitx_5fto_5ffcp_2eproto,
    "fcitx_to_fcp.proto",
    &descriptor_table_fcitx_5fto_5ffcp_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_fcitx_5fto_5ffcp_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_fcitx_5fto_5ffcp_2eproto,
    file_level_service_descriptors_fcitx_5fto_5ffcp_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fcitx_5fto_5ffcp_2eproto_getter() {
  return &descriptor_table_fcitx_5fto_5ffcp_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fcitx_5fto_5ffcp_2eproto(&descriptor_table_fcitx_5fto_5ffcp_2eproto);
const ::google::protobuf::EnumDescriptor* KeyEvent_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_fcitx_5fto_5ffcp_2eproto);
  return file_level_enum_descriptors_fcitx_5fto_5ffcp_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t KeyEvent_internal_data_[] = {
    1441792u, 224u, 1882984192u, 0u, 4294950912u, 255u, 0u, 4294705152u, 4095u, };
bool KeyEvent_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, KeyEvent_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
