// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ims_send.proto

#include "ims_send.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr FcitxEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : event_{static_cast< ::KeyEvent >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FcitxEvent::FcitxEvent(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FcitxEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FcitxEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FcitxEventDefaultTypeInternal() {}
  union {
    FcitxEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FcitxEventDefaultTypeInternal _FcitxEvent_default_instance_;
static ::_pb::Metadata file_level_metadata_ims_5fsend_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ims_5fsend_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ims_5fsend_2eproto = nullptr;
const ::uint32_t TableStruct_ims_5fsend_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::FcitxEvent, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::FcitxEvent, _impl_.event_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::FcitxEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_FcitxEvent_default_instance_._instance,
};
const char descriptor_table_protodef_ims_5fsend_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016ims_send.proto\"&\n\nFcitxEvent\022\030\n\005event\030"
    "\001 \001(\0162\t.KeyEvent*\351\007\n\010KeyEvent\022\t\n\005NUM_0\020\000"
    "\022\t\n\005NUM_1\020\001\022\t\n\005NUM_2\020\002\022\t\n\005NUM_3\020\003\022\t\n\005NUM"
    "_4\020\004\022\t\n\005NUM_5\020\005\022\t\n\005NUM_6\020\006\022\t\n\005NUM_7\020\007\022\t\n"
    "\005NUM_8\020\010\022\t\n\005NUM_9\020\t\022\t\n\005A_LWR\020d\022\t\n\005B_LWR\020"
    "e\022\t\n\005C_LWR\020f\022\t\n\005D_LWR\020g\022\t\n\005E_LWR\020h\022\t\n\005F_"
    "LWR\020i\022\t\n\005G_LWR\020j\022\t\n\005H_LWR\020k\022\t\n\005I_LWR\020l\022\t"
    "\n\005J_LWR\020m\022\t\n\005K_LWR\020n\022\t\n\005L_LWR\020o\022\t\n\005M_LWR"
    "\020p\022\t\n\005N_LWR\020q\022\t\n\005O_LWR\020r\022\t\n\005P_LWR\020s\022\t\n\005Q"
    "_LWR\020t\022\t\n\005R_LWR\020u\022\t\n\005S_LWR\020v\022\t\n\005T_LWR\020w\022"
    "\t\n\005U_LWR\020x\022\t\n\005V_LWR\020y\022\t\n\005W_LWR\020z\022\t\n\005X_LW"
    "R\020{\022\t\n\005Y_LWR\020|\022\t\n\005Z_LWR\020}\022\n\n\005A_UPR\020\310\001\022\n\n"
    "\005B_UPR\020\311\001\022\n\n\005C_UPR\020\312\001\022\n\n\005D_UPR\020\313\001\022\n\n\005E_U"
    "PR\020\314\001\022\n\n\005F_UPR\020\315\001\022\n\n\005G_UPR\020\316\001\022\n\n\005H_UPR\020\317"
    "\001\022\n\n\005I_UPR\020\320\001\022\n\n\005J_UPR\020\321\001\022\n\n\005K_UPR\020\322\001\022\n\n"
    "\005L_UPR\020\323\001\022\n\n\005M_UPR\020\324\001\022\n\n\005N_UPR\020\325\001\022\n\n\005O_U"
    "PR\020\326\001\022\n\n\005P_UPR\020\327\001\022\n\n\005Q_UPR\020\330\001\022\n\n\005R_UPR\020\331"
    "\001\022\n\n\005S_UPR\020\332\001\022\n\n\005T_UPR\020\333\001\022\n\n\005U_UPR\020\334\001\022\n\n"
    "\005V_UPR\020\335\001\022\n\n\005W_UPR\020\336\001\022\n\n\005X_UPR\020\337\001\022\n\n\005Y_U"
    "PR\020\340\001\022\n\n\005Z_UPR\020\341\001\022\t\n\005COMMA\020\n\022\n\n\006PERIOD\020\013"
    "\022\r\n\tQEST_MARK\020\014\022\r\n\tEXCL_MARK\020\r\022\016\n\nSEMI_C"
    "OLON\020\016\022\r\n\tDBL_QUOTE\020\017\022\r\n\tSGL_QUOTE\020\020\022\r\n\t"
    "BRKT_OPEN\020\021\022\016\n\nBRKT_CLOSE\020\022\022\t\n\005SLASH\020\023\022\r"
    "\n\tBACKSLASH\020\024\022\014\n\010ELLIPSIS\020\025\022\t\n\005ENTER\020\036\022\t"
    "\n\005SPACE\020\037\022\t\n\005MINUS\020 \022\t\n\005EQUAL\020!\022\006\n\002UP\020(\022"
    "\010\n\004DOWN\020)\022\010\n\004LEFT\020*\022\t\n\005RIGHT\020+\022\t\n\005SHIFT\020"
    "2\022\010\n\004CTRL\0203\022\007\n\003ALT\0204b\006proto3"
};
static ::absl::once_flag descriptor_table_ims_5fsend_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ims_5fsend_2eproto = {
    false,
    false,
    1068,
    descriptor_table_protodef_ims_5fsend_2eproto,
    "ims_send.proto",
    &descriptor_table_ims_5fsend_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ims_5fsend_2eproto::offsets,
    file_level_metadata_ims_5fsend_2eproto,
    file_level_enum_descriptors_ims_5fsend_2eproto,
    file_level_service_descriptors_ims_5fsend_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ims_5fsend_2eproto_getter() {
  return &descriptor_table_ims_5fsend_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ims_5fsend_2eproto(&descriptor_table_ims_5fsend_2eproto);
const ::google::protobuf::EnumDescriptor* KeyEvent_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ims_5fsend_2eproto);
  return file_level_enum_descriptors_ims_5fsend_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t KeyEvent_internal_data_[] = {
    1441792u, 224u, 1882984192u, 0u, 4294950912u, 255u, 0u, 4294705152u, 4095u, };
bool KeyEvent_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, KeyEvent_internal_data_);
}
// ===================================================================

class FcitxEvent::_Internal {
 public:
};

FcitxEvent::FcitxEvent(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FcitxEvent)
}
FcitxEvent::FcitxEvent(
    ::google::protobuf::Arena* arena, const FcitxEvent& from)
    : FcitxEvent(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FcitxEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FcitxEvent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.event_ = {};
}
FcitxEvent::~FcitxEvent() {
  // @@protoc_insertion_point(destructor:FcitxEvent)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FcitxEvent::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FcitxEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:FcitxEvent)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.event_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FcitxEvent::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FcitxEvent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FcitxEvent_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .KeyEvent event = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FcitxEvent, _impl_.event_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FcitxEvent, _impl_.event_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .KeyEvent event = 1;
    {PROTOBUF_FIELD_OFFSET(FcitxEvent, _impl_.event_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FcitxEvent::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FcitxEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .KeyEvent event = 1;
  if (this->_internal_event() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_event(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FcitxEvent)
  return target;
}

::size_t FcitxEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FcitxEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .KeyEvent event = 1;
  if (this->_internal_event() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_event());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FcitxEvent::_class_data_ = {
    FcitxEvent::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FcitxEvent::GetClassData() const {
  return &_class_data_;
}

void FcitxEvent::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FcitxEvent*>(&to_msg);
  auto& from = static_cast<const FcitxEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FcitxEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_event() != 0) {
    _this->_internal_set_event(from._internal_event());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FcitxEvent::CopyFrom(const FcitxEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FcitxEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FcitxEvent::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FcitxEvent::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FcitxEvent::InternalSwap(FcitxEvent* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.event_, other->_impl_.event_);
}

::google::protobuf::Metadata FcitxEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ims_5fsend_2eproto_getter, &descriptor_table_ims_5fsend_2eproto_once,
      file_level_metadata_ims_5fsend_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
